language: c
dist: trusty
addons:
  apt:
    packages:
      - automake
      - autotools-dev
      - libcap-dev
script:
  - env NOCONFIGURE=1 ./autogen.sh
  - mkdir build
  - cd build && ../configure --prefix=/usr
  - make -j 2
  - make check
  - sudo make install
  - curl --upload-file /usr/bin/bwrap https://transfer.sh/bwrap
